### ISSUE TITLE
Do I have to record the other maps callout points myself? 

### ISSUE THREAD

**Issue by TheSoliderror** [hosseinpourziyaie/IW6X_SCRIPTS#1]
I forgot about this mod for quite some time and, I found a reference to the mod in one of my old Server plugin ideas text files. When using the mod it does what it says on only some maps, and I was wondering if I had to map out the points myself or not for the rest of the maps? It seems your discord user was deleted so I couldnt ask for help there, all I really need to know is if I need to make them, or if you already have some. If I have to make them could you please explain a little to help record the points in game.

**Comment by hosseinpourziyaie** [comment]
showing player's position callout need map locations data that is stored in lua plugin core.
I ve already included data for 4 maps in this code. im not planning to record other maps data for now. its such a hard process to effort

**Comment by hosseinpourziyaie** [comment]
> I forgot about this mod for quite some time and, I found a reference to the mod in one of my old Server plugin ideas text files. When using the mod it does what it says on only some maps, and I was wondering if I had to map out the points myself or not for the rest of the maps? It seems your discord user was deleted so I couldnt ask for help there, all I really need to know is if I need to make them, or if you already have some. If I have to make them could you please explain a little to help record the points in game.

there is a dev tool I have included with code that is commented out by default. I will try to add full explanation document of how  whole idea works and how to use dev tool eta 1week. 
or if you know programming basics you can already read the code itself and find out how it works
